INSERT INTO public.about_page (id, mission, vision, title, content, images, created_at, updated_at) VALUES (2, 'Çiftçilerimize en yenilikçi tarım teknolojilerini ve en kaliteli ürünleri sunarak, onların verimliliğini ve gelirini artırmak. Sürdürülebilir tarım uygulamalarını yaygınlaştırarak hem toprağımızı korumak hem de gelecek nesillere daha verimli araziler bırakmak en temel amacımızdır.', 'Türkiye''nin fındık ve tarım sektöründe, teknoloji kullanımı, danışmanlık hizmetleri ve ürün kalitesiyle referans gösterilen lider bir marka olmak. Tarımda dijital dönüşüme öncülük ederek, sektörü geleceğe taşımak.', NULL, 'AKAYDIN TARIM, 2023 yılında, ömrünü fındık üretimine adamış olan Aydın Ak tarafından kurulmuştur. Kurucumuz Aydın Ak, yılların getirdiği deneyimi ve geleneksel üretim bilgisini, modern tarım teknolojileriyle birleştirerek sektöre yenilikçi bir soluk kazandırmayı hedeflemiştir.
INSERT INTO public.blog_posts (id, title, summary, content, author, date, image_url, excerpt, views, seo_title, seo_description, seo_keywords, created_at, updated_at) VALUES (12, 'Fındığın Sağlık Faydaları: Her Gün Bir Avuç Fındık', NULL, '
INSERT INTO public.blog_posts (id, title, summary, content, author, date, image_url, excerpt, views, seo_title, seo_description, seo_keywords, created_at, updated_at) VALUES (13, '🌿 Toprağa Saygı, Geleceğe Yatırım: Organomineral Gübre ile Verimli Bir Yolculuk', NULL, 'Ben Aydın Ak.
INSERT INTO public.blog_posts (id, title, summary, content, author, date, image_url, excerpt, views, seo_title, seo_description, seo_keywords, created_at, updated_at) VALUES (14, '✂️ Fındık Üretiminde Budamanın Önemi', NULL, 'Ben Aydın Ak.
INSERT INTO public.blog_posts (id, title, summary, content, author, date, image_url, excerpt, views, seo_title, seo_description, seo_keywords, created_at, updated_at) VALUES (15, 'Fındık İşleme Nedir? Detaylı Rehber', NULL, '<h2>???? Fındık İşleme Nedir?</h2>
INSERT INTO public.blog_posts (id, title, summary, content, author, date, image_url, excerpt, views, seo_title, seo_description, seo_keywords, created_at, updated_at) VALUES (16, 'Fındık Kırma Makineleri Nasıl Çalışır? Teknik Rehber', NULL, '<h2>⚙️ Fındık Kırma Makineleri Nasıl Çalışır?</h2>
INSERT INTO public.blog_posts (id, title, summary, content, author, date, image_url, excerpt, views, seo_title, seo_description, seo_keywords, created_at, updated_at) VALUES (17, 'Hendek Bölgesinde Fındık İşleme Avantajları', NULL, '<h2>???? Hendek Bölgesinde Fındık İşleme Avantajları</h2>
INSERT INTO public.hazelnut_prices (id, price, daily_change, change_percentage, source, scraped_price, last_scraped_at, update_mode, scraping_enabled, notes, created_at, updated_at) VALUES (1, 283.75, 0.00, 0.00, 'scraped', 283.75, '2026-07-29 12:04:26.559582', 'manual', 1, 'Otomatik scraping - 29.07.2026 12:04:26', '2026-07-29 12:04:26.559582', '2026-07-29 12:04:26.559582');
INSERT INTO public.hero_content (id, title, subtitle, description, cta, background_gradient, background_image, is_active, order_index, created_at, updated_at) VALUES (8, 'Fındık Üretiminizi', 'Bir Sonraki Seviyeye Taşıyın', 'Modern tarım teknikleri ve uzman danışmanlık hizmetleriyle verimliliğinizi artırın.', 'Hemen Başlayın', 'from-green-600 via-green-700 to-blue-800', '/uploads/background_image-1785315368594-597197766.webp', 1, 1, '2025-10-31 14:03:03', '2025-10-31 16:03:06');
INSERT INTO public.hero_content (id, title, subtitle, description, cta, background_gradient, background_image, is_active, order_index, created_at, updated_at) VALUES (9, 'Organomineral Gübreler ile', 'Doğal ve Verimli Üretim', 'Çevre dostu gübre çözümlerimizle hem toprağınızı hem de ürününüzü koruyun.', 'Ürünlerimizi Keşfedin', 'from-green-600 via-green-700 to-blue-800', '/uploads/background_image-1785315394571-42033454.webp', 1, 1, '2025-10-31 15:04:28', '2025-10-31 15:19:06');
INSERT INTO public.products (id, name, description, category, price, image_url, images, is_featured, seo_title, seo_description, seo_keywords, created_at, updated_at) VALUES (17, 'Kavrulmuş Fındık', 'Kavrulmuş Fındık', 'Fındık Ürünleri', 0.00, '/akaydin-tarim/uploads/product/1761920665_ab31e4ab115e6559.jpg', '["\/akaydin-tarim\/uploads\/product\/1761920665_ab31e4ab115e6559.jpg"]', 1, NULL, NULL, NULL, '2025-10-31 17:10:09', '2025-10-31 17:24:25');
INSERT INTO public.products (id, name, description, category, price, image_url, images, is_featured, seo_title, seo_description, seo_keywords, created_at, updated_at) VALUES (18, 'OrganoMineral Gübre', '15 15 15 Organomineral gübre', 'Gübreler', 0.00, '/akaydin-tarim/uploads/product/1761920556_47d0d36298729bc6.jpg', '["\/akaydin-tarim\/uploads\/product\/1761920556_47d0d36298729bc6.jpg"]', 1, NULL, NULL, NULL, '2025-10-31 17:20:55', '2025-10-31 17:22:37');
INSERT INTO public.products (id, name, description, category, price, image_url, images, is_featured, seo_title, seo_description, seo_keywords, created_at, updated_at) VALUES (19, 'Fındık Ezmesi', 'Cam kananoz da fındık ezmesi', 'Fındık  Ürünleri', 0.00, '/akaydin-tarim/uploads/product/1761920513_2df6c81ad19d61cd.jpg', '["\/akaydin-tarim\/uploads\/product\/1761920513_2df6c81ad19d61cd.jpg"]', 1, NULL, NULL, NULL, '2025-10-31 17:21:53', '2025-10-31 17:21:53');
INSERT INTO public.products (id, name, description, category, price, image_url, images, is_featured, seo_title, seo_description, seo_keywords, created_at, updated_at) VALUES (20, 'Kabuklu Fındık', 'Taze Kabuklu Fındık', 'Fındık Ürünleri', 0.00, '/akaydin-tarim/uploads/product/1761920635_f83c3c947342f579.jpg', '["\/akaydin-tarim\/uploads\/product\/1761920635_f83c3c947342f579.jpg"]', 1, NULL, NULL, NULL, '2025-10-31 17:23:55', '2025-10-31 17:23:55');
INSERT INTO public.services (id, title, description, icon_name, image_url, seo_title, seo_description, seo_keywords, created_at, updated_at) VALUES (16, 'Fındık Üretimi Danışmanlığı', 'Modern tarım teknikleri ve uzman ekibimizle verimliliğinizi artırıyoruz. Toprak analizinden hasat planlamasına kadar yanınızdayız.', 'leaf', '/akaydin-tarim/akaydin/images/DRON.jpeg', 'Fındık Üretimi Danışmanlığı - Akaydin Tarım', 'Modern tarım teknikleri ve uzman ekibimizle fındık üretim verimliliğinizi artırıyoruz. Toprak analizi, gübreleme, budama ve hasat planlaması hizmetleri.', 'fındık üretimi, tarım danışmanlığı, toprak analizi, hasat planlaması, fındık yetiştirme', '2025-10-31 16:07:39', '2025-10-31 16:16:41');
INSERT INTO public.services (id, title, description, icon_name, image_url, seo_title, seo_description, seo_keywords, created_at, updated_at) VALUES (17, 'Fındık İşleme Hizmetleri', 'Son teknoloji makinelerimizle fındık kırma, kavurma ve vakumlu paketleme hizmetleri sunuyoruz. Ürününüzün değerini koruyoruz.', 'settings', '/akaydin-tarim/uploads/service/1761919091_5c3119074a561f76.jpg', 'Fındık İşleme Hizmetleri - Akaydin Tarım', 'Son teknoloji makinelerimizle fındık kırma, kavurma ve vakumlu paketleme hizmetleri. Ürününüzün kalitesini ve değerini koruyoruz.', 'fındık işleme, fındık kırma, fındık kavurma, vakumlu paketleme, fındık paketleme', '2025-10-31 16:07:50', '2025-10-31 16:58:11');
INSERT INTO public.services (id, title, description, icon_name, image_url, seo_title, seo_description, seo_keywords, created_at, updated_at) VALUES (19, 'Organomineral Gübre Bayiliği', 'Toprağınızın ihtiyacı olan zengin içerikli, yüksek kaliteli organomineral gübre çeşitlerimizle fındık bahçenizi canlandırın.', 'package', '/akaydin-tarim/uploads/service/1761917531_3382cdbd50dbfa65.jpg', 'Organomineral Gübre Bayiliği - Akaydin Tarım', 'Zengin içerikli, yüksek kaliteli organomineral gübre çeşitlerimizle toprağınızı besleyin. Fındık bahçenizin verimi için güvenilir çözüm.', 'organomineral gübre, toprak gübresi, fındık gübresi, tarım gübresi, organik gübre', '2025-10-31 16:08:08', '2025-10-31 16:32:11');
